"""
Prompt generation utilities for reflection feature.

Contains templates and formatting logic for:
- Constitutional approval prompts
- Analysis prompts
- GitHub ticket generation
- Self-model update prompts
"""

from typing import Dict, Any
from .models import ImprovementProposal, Insight, ChangeType


def format_approval_prompt(proposal: ImprovementProposal) -> str:
    """
    Format a constitutional approval prompt for self-modification.

    Args:
        proposal: The improvement proposal to format

    Returns:
        Formatted prompt string for constitutional approval
    """
    return f"""
The agent is requesting permission to modify itself.

## Proposed Change
- Type: {proposal.change_type.value}
- Title: {proposal.title}

## Description
{proposal.description}

## Proposed Modification
{proposal.proposed_change}

## Constitutional Questions
1. Does this serve the user's interests?
2. Is this within the agent's mandate?
3. Could this cause harm?
4. Is this reversible?
"""


def format_github_issue_title(insight: Insight) -> str:
    """
    Format a title for a GitHub issue based on an insight.

    Args:
        insight: The insight to create a title for

    Returns:
        Formatted issue title
    """
    insight_type = insight.type.value.title()
    return f"[{insight_type}] {insight.title}"


def format_github_issue_body(insight: Insight, agent_id: str) -> str:
    """
    Format the body content for a GitHub issue based on an insight.

    Args:
        insight: The insight to create an issue for
        agent_id: The agent identifier

    Returns:
        Formatted issue body in markdown
    """
    confidence_percent = int(insight.confidence * 100)

    body = f"""## Agent Self-Reflection Insight

**Agent ID:** `{agent_id}`
**Insight Type:** {insight.type.value.title()}
**Confidence:** {confidence_percent}%
**Actionable:** {'Yes' if insight.actionable else 'No'}

### Description
{insight.description}

### Evidence
"""

    if insight.evidence:
        for evidence_item in insight.evidence:
            body += f"- `{evidence_item}`\n"
    else:
        body += "- No specific evidence recorded\n"

    if insight.suggested_action:
        body += f"""
### Suggested Action
{insight.suggested_action}
"""

    body += f"""
### Metadata
- **Created:** {insight.created_at.isoformat()}
- **Source:** Agent self-reflection system

---
*This issue was automatically generated by the agent's reflection system.*
"""

    return body


def format_self_model_update_prompt(insights: list, current_model: Dict[str, Any]) -> str:
    """
    Format a prompt for self-model updates based on insights.

    Args:
        insights: List of insights to incorporate
        current_model: Current self-model data

    Returns:
        Formatted prompt for self-model update approval
    """
    insights_summary = []
    for insight in insights:
        insights_summary.append(f"- [{insight.type.value}] {insight.title}: {insight.description[:100]}...")

    insights_text = "\n".join(insights_summary)

    return f"""
The agent is requesting permission to update its self-model based on recent insights.

## Current Model Summary
- Personality Traits: {current_model.get('personality_traits', {})}
- Communication Style: {current_model.get('communication_style', {})}
- Behavior Patterns: {len(current_model.get('behavior_patterns', []))} patterns learned

## New Insights to Incorporate
{insights_text}

## Constitutional Questions
1. Will these changes serve user interests better?
2. Do these insights reflect genuine improvement opportunities?
3. Could incorporating these insights cause harm?
4. Can these changes be reversed if needed?

The agent will use these insights to refine its personality traits, communication preferences, and learned behaviors.
"""


def format_training_summary(iterations: int, health_trend: list) -> str:
    """
    Format a summary message for training cycle completion.

    Args:
        iterations: Number of iterations completed
        health_trend: List of health data per iteration

    Returns:
        Formatted summary message
    """
    if not health_trend:
        return f"Training cycle completed {iterations} iterations - no health data available"

    final_health = health_trend[-1]
    is_healthy = final_health.get('healthy', False)
    critical_count = final_health.get('critical', 0)
    warn_count = final_health.get('warn', 0)

    status = "HEALTHY" if is_healthy else "NEEDS ATTENTION"

    summary = f"Training cycle completed {iterations} iterations - Status: {status}"

    if critical_count > 0:
        summary += f" ({critical_count} critical issues)"
    elif warn_count > 0:
        summary += f" ({warn_count} warnings)"

    return summary


def format_reflection_layer_summary(layer_name: str, checks: list) -> str:
    """
    Format a summary for a reflection layer's results.

    Args:
        layer_name: Name of the reflection layer
        checks: List of check results

    Returns:
        Formatted summary string
    """
    total = len(checks)
    passed = sum(1 for check in checks if check.get('status') == 'PASS')
    failed = sum(1 for check in checks if check.get('status') in ['FAIL', 'WARN'])
    critical = sum(1 for check in checks if
                  check.get('status') == 'FAIL' and
                  check.get('severity') == 'CRITICAL')

    summary = f"{layer_name.title()} Layer: {passed}/{total} checks passed"

    if critical > 0:
        summary += f" ({critical} critical failures)"
    elif failed > 0:
        summary += f" ({failed} issues)"

    return summary


# Constitutional prompt templates for different change types
CONSTITUTIONAL_PROMPTS = {
    ChangeType.PROMPT: """
This change will modify how the agent thinks and reasons by adding guidance to its system prompts.

Prompt modifications can significantly impact behavior and decision-making.
""",
    ChangeType.BEHAVIOR: """
This change will create a new behavioral rule that triggers under specific conditions.

Behavioral rules directly influence the agent's actions and responses.
""",
    ChangeType.RESPONSE_STYLE: """
This change will modify how the agent communicates and formats its responses.

Style changes affect user experience and interaction quality.
""",
    ChangeType.TOOL_USAGE: """
This change will modify how the agent uses its available tools and capabilities.

Tool usage changes can impact the agent's effectiveness and safety.
""",
}


def get_change_type_context(change_type: ChangeType) -> str:
    """
    Get contextual information for a specific change type.

    Args:
        change_type: The type of change being proposed

    Returns:
        Contextual information about the change type
    """
    return CONSTITUTIONAL_PROMPTS.get(change_type, "This change will modify agent behavior.")