"""Process-local provenance for the sovereign API key.

The HTTP server may mint a temporary bootstrap key so a local development
session remains usable.  That key authenticates requests for the lifetime of
the process, but it is not durable authority for a whole-host mutation whose
evidence must survive a restart.  Keep only a fingerprint here: callers can
distinguish that bootstrap credential without retaining another copy of the
secret.
"""

from __future__ import annotations

import hashlib
import hmac
import os


_ephemeral_key_fingerprint: bytes | None = None
_EPHEMERAL_KEY_FINGERPRINT_ENV = (
    "KESTREL_INTERNAL_EPHEMERAL_SOVEREIGN_KEY_FINGERPRINT"
)


def _fingerprint(key: str) -> bytes:
    return hashlib.sha256(key.encode("utf-8")).digest()


def sovereign_key_fingerprint(key: str) -> str:
    """Return the non-secret binding recorded on an authenticated request."""

    return _fingerprint(normalize_sovereign_api_key(key)).hex()


def normalize_sovereign_api_key(key: str) -> str:
    """Apply the exact normalization used by HTTP sovereign authentication."""

    if len(key) >= 2 and key[0] == key[-1] and key[0] in {'"', "'"}:
        return key[1:-1]
    return key


def mark_ephemeral_sovereign_key(key: str) -> None:
    """Record that *key* was generated by this boot, including for children."""

    global _ephemeral_key_fingerprint
    _ephemeral_key_fingerprint = _fingerprint(key)
    # Separately hosted agents and the detached restart child inherit the host
    # environment but import this module afresh. Carry only the fingerprint so
    # they retain the parent's fail-closed provenance without another copy of
    # the credential.
    os.environ[_EPHEMERAL_KEY_FINGERPRINT_ENV] = (
        _ephemeral_key_fingerprint.hex()
    )


def is_ephemeral_sovereign_key(key: str) -> bool:
    """Return whether *key* is the process-generated bootstrap credential."""

    candidate = _fingerprint(key)
    fingerprints = []
    if _ephemeral_key_fingerprint is not None:
        fingerprints.append(_ephemeral_key_fingerprint)
    inherited = os.environ.get(_EPHEMERAL_KEY_FINGERPRINT_ENV, "")
    try:
        if len(inherited) == 64:
            fingerprints.append(bytes.fromhex(inherited))
    except ValueError:
        pass
    return any(hmac.compare_digest(candidate, item) for item in fingerprints)
