"""Project-root and package-root resolution.

Two questions, two answers:

  1. **Where does the user's data live?** — agent DBs, ``multi_agent.toml``,
     ``kestrel.toml``, ``.env``, ``logs/``. Answered by :func:`project_dir`.
  2. **Where do bundled package assets live?** — prompts, templates,
     themes, the constitution markdown. Answered by :func:`package_dir`.

The historical answer for both was the same: ``Path(__file__).parent.parent``.
That worked when ``kestrel-sovereign`` was always run from a source clone
because the package and the project happened to share a parent. After
``pip install kestrel-sovereign``, the package lives in
``site-packages/kestrel_sovereign/`` and ``parent.parent`` resolves to
``site-packages/``. Writing user data there is silent data loss on
``pip install --upgrade`` (the new package replaces the old directory),
and the server subprocess gets ``cwd=site-packages``, so any code that
does ``Path("kestrel.toml")`` reads from the wrong place.

:func:`project_dir` resolves the user's project, in priority order:

    1. ``KESTREL_HOME`` environment variable, if set — explicit override.
    2. CWD or any ancestor that contains a project marker file
       (``multi_agent.toml``, ``kestrel.toml``, ``.env``, or a
       ``kestrel_sovereign`` package source under ``./kestrel_sovereign/``).
       This is the source-clone case: the user is somewhere inside their
       repo, we find it.
    3. Source-clone heuristic: if the package itself is *not* inside
       ``site-packages`` (so this is an editable / source install whose
       parent is the repo), use ``Path(__file__).parent.parent``.
    4. Fallback: ``~/.kestrel/``. Pip-installed users with no project
       in CWD land here. We create the directory the first time we
       resolve to it so subsequent writes succeed.

The resolver is **not cached** at module import time because callers may
``chdir`` between invocations (notably the integration test suite). It
*is* memoized for the lifetime of a single Python process keyed on
``(KESTREL_HOME, getcwd())`` to avoid filesystem stat thrashing.

Setting ``KESTREL_HOME`` is also the recommended pattern for callers
that want full control: tests pass an explicit value, Docker images pin
``/data``, ops can move user data to a different volume.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

#: Marker files that identify a directory as a Kestrel project root.
#: Order matters only for documentation — any one match is enough.
_PROJECT_MARKERS: tuple[str, ...] = (
    "multi_agent.toml",
    "kestrel.toml",
    ".env",
)

#: Sentinel that identifies a source clone: the project root contains
#: a ``kestrel_sovereign`` directory with the package source. This lets
#: ``cd kestrel-sovereign && kestrel start`` work even before any of the
#: marker files have been generated by the wizard.
_PACKAGE_SENTINEL = "kestrel_sovereign"


def package_dir() -> Path:
    """Absolute path to the installed ``kestrel_sovereign`` package.

    Use this for reading bundled assets that ship with the wheel:
    prompts, templates, themes, ``data/KESTREL_CONSTITUTION.md``. Never
    use it for paths the user will read or write.
    """
    return Path(__file__).resolve().parent


def project_dir() -> Path:
    """Resolve the user's Kestrel project directory.

    See module docstring for the priority order. The result is always
    an absolute, resolved path. The directory is created on first
    resolve if and only if we land on the ``~/.kestrel`` fallback —
    every other branch refuses to create directories the user didn't
    ask for.
    """
    cwd = Path.cwd()
    explicit_home = os.environ.get("KESTREL_HOME")
    return _resolve_cached(explicit_home, str(cwd))


@lru_cache(maxsize=64)
def _resolve_cached(kestrel_home: str | None, cwd_str: str) -> Path:
    """Pure resolver — every input that affects the answer is an argument.

    Memoized so repeated lookups within one process don't restat the
    filesystem. ``lru_cache`` is keyed on the tuple of arguments, which
    means a subsequent ``os.chdir`` will produce a fresh lookup with the
    new ``cwd_str``. ``KESTREL_HOME`` is read once per resolution at
    the public-API boundary and passed in here, so an env-var change
    after the first call also produces a fresh entry.
    """
    if kestrel_home:
        return Path(kestrel_home).expanduser().resolve()

    cwd = Path(cwd_str).resolve()
    found = _walk_up_for_markers(cwd)
    if found is not None:
        return found

    pkg = package_dir()
    if not _is_inside_site_packages(pkg):
        # Source / editable install: parent of the package is the repo.
        return pkg.parent

    fallback = Path.home() / ".kestrel"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback.resolve()


def _walk_up_for_markers(start: Path) -> Path | None:
    """Search ``start`` and every ancestor for a project marker.

    Returns the first directory that contains any of ``_PROJECT_MARKERS``
    or a ``kestrel_sovereign`` package source. Stops at the filesystem
    root.
    """
    for candidate in (start, *start.parents):
        if any((candidate / marker).exists() for marker in _PROJECT_MARKERS):
            return candidate
        sentinel = candidate / _PACKAGE_SENTINEL
        if sentinel.is_dir() and (sentinel / "__init__.py").exists():
            return candidate
    return None


def _is_inside_site_packages(path: Path) -> bool:
    """True iff ``path`` is under any ``site-packages`` segment.

    Using the segment name rather than ``site.getsitepackages()`` so we
    correctly handle every flavor of install: system, user, virtualenv,
    venv-in-venv, pipx, uv-tool, conda. They all bury the package under
    a directory literally named ``site-packages``.
    """
    parts = path.parts
    return "site-packages" in parts


def reset_cache() -> None:
    """Clear the resolver cache.

    Tests that ``monkeypatch.setenv("KESTREL_HOME", ...)`` mid-run, or
    ``chdir`` and re-resolve, should call this to force a fresh lookup.
    Production code never needs it — the cache is keyed on the inputs,
    so a real change in either re-misses naturally.
    """
    _resolve_cached.cache_clear()
