"""Project-root and package-root resolution.

Four questions, four answers:

  1. **Where does the user's data live?** — agent DBs, ``multi_agent.toml``,
     ``kestrel.toml``, ``.env``, ``logs/``. Answered by :func:`project_dir`.
  2. **Where do bundled package assets live?** — prompts, templates,
     themes, the constitution markdown. Answered by :func:`package_dir`.
  3. **Where does implicit host-runtime state live?** — supervised services,
     fleet/host feature state, and other data that must not appear merely
     because Kestrel launched from a clone. Answered by :func:`host_data_dir`.
  4. **How does that home's ``.env`` reach the process?** — deliberately, at an
     entry point, naming the home. Answered by :func:`load_project_env`.

The historical answer for the first two was the same:
``Path(__file__).parent.parent``.
That worked when ``kestrel-sovereign`` was always run from a source clone
because the package and the project happened to share a parent. After
``pip install kestrel-sovereign``, the package lives in
``site-packages/kestrel_sovereign/`` and ``parent.parent`` resolves to
``site-packages/``. Writing user data there is silent data loss on
``pip install --upgrade`` (the new package replaces the old directory),
and the server subprocess gets ``cwd=site-packages``, so any code that
does ``Path("kestrel.toml")`` reads from the wrong place.

:func:`project_dir` resolves the user's project, in priority order:

    1. ``KESTREL_HOME`` environment variable, if set — explicit override.
    2. CWD or any ancestor that contains a project marker file
       (``multi_agent.toml``, ``kestrel.toml``, ``.env``, or a
       ``kestrel_sovereign`` package source under ``./kestrel_sovereign/``).
       This is the source-clone case: the user is somewhere inside their
       repo, we find it.
    3. Source-clone heuristic: if the package itself is *not* inside
       ``site-packages`` (so this is an editable / source install whose
       parent is the repo), use ``Path(__file__).parent.parent``.
    4. Fallback: ``~/.kestrel/``. Pip-installed users with no project
       in CWD land here. We create the directory the first time we
       resolve to it so subsequent writes succeed.

The resolver is **not cached** at module import time because callers may
``chdir`` between invocations (notably the integration test suite). It
*is* memoized for the lifetime of a single Python process keyed on
``(KESTREL_HOME, getcwd())`` to avoid filesystem stat thrashing.

Setting ``KESTREL_HOME`` is also the recommended pattern for callers
that want full control: tests pass an explicit value, Docker images pin
``/data``, ops can move user data to a different volume.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

#: Marker files that identify a directory as a Kestrel project root.
#: Order matters only for documentation — any one match is enough.
_PROJECT_MARKERS: tuple[str, ...] = (
    "multi_agent.toml",
    "kestrel.toml",
    ".env",
)

#: Sentinel that identifies a source clone: the project root contains
#: a ``kestrel_sovereign`` directory with the package source. This lets
#: ``cd kestrel-sovereign && kestrel start`` work even before any of the
#: marker files have been generated by the wizard.
_PACKAGE_SENTINEL = "kestrel_sovereign"


def package_dir() -> Path:
    """Absolute path to the installed ``kestrel_sovereign`` package.

    Use this for reading bundled assets that ship with the wheel:
    prompts, templates, themes, ``data/KESTREL_CONSTITUTION.md``. Never
    use it for paths the user will read or write.
    """
    return Path(__file__).resolve().parent


def project_dir() -> Path:
    """Resolve the user's Kestrel project directory.

    See module docstring for the priority order. The result is always
    an absolute, resolved path. The directory is created on first
    resolve if and only if we land on the ``~/.kestrel`` fallback —
    every other branch refuses to create directories the user didn't
    ask for.
    """
    cwd = Path.cwd()
    explicit_home = os.environ.get("KESTREL_HOME")
    return _resolve_cached(explicit_home, str(cwd))


def load_project_env(home: Path, *, exclude: tuple[str, ...] = ()) -> None:
    """Load a resolved project home's ``.env`` into ``os.environ``.

    The one place a process may pull ``.env`` into its environment, and it
    belongs to a *named* home rather than to whatever directory the process
    happened to start in. Import-time and constructor-time loads have twice
    been custody defects: ``inception_service`` seeded the wrong
    ``KESTREL_DATA_KEY`` from the current directory (#2468), and
    ``LLMService.__init__`` re-ran a bare ``load_dotenv()`` on every
    construction, silently resurrecting variables a caller had deliberately
    unset (#2896).

    Uses python-dotenv's own parser (``dotenv_values``) — the same one the
    runtime uses, so a plain value is the identical byte string boot will see —
    and ``setdefault`` semantics so a genuinely exported value stays
    authoritative.

    Equivalent to ``load_dotenv(override=False)`` for every value that does not
    interpolate another variable. It is **not** equivalent for ``${VAR}``:
    ``dotenv_values`` fixes ``override=True`` internally, so a reference
    resolves against the file's own bindings where ``load_dotenv(override=
    False)`` would prefer an exported one. No shipped ``.env`` template uses
    interpolation, and ``server.py`` still boots through the other call, so the
    two can disagree there until they are aligned.

    ``exclude`` names keys to skip. The data key is excluded when this runs
    *before* custody resolution so that seeding the persisted value into
    ``os.environ`` cannot mask an exported⇄persisted conflict (#2468).
    """
    env_path = home / ".env"
    if not env_path.exists():
        return
    from dotenv import dotenv_values

    for key, value in dotenv_values(str(env_path)).items():
        if value is None or key in exclude:
            continue
        os.environ.setdefault(key, value)


def spawned_agent_env(project_dir: Path) -> dict:
    """The environment ``kestrel start`` hands a spawned agent process.

    The launch authority for every agent in ``multi_agent.toml``, factored out
    of ``multi_agent.process_manager.ProcessManager._load_env`` so that a tool
    reasoning about a running agent can ask the launcher instead of guessing.

    Note the precedence, which is the **opposite** of :func:`load_project_env`
    above: the launcher copies ``os.environ`` and then lets the project ``.env``
    overwrite it, so the file wins. That disagreement is real and predates this
    function — a spawned agent is configured by the file, while a process that
    boots through ``load_project_env`` keeps its exported values. Reconciling
    the two is a boot-semantics change, not something to settle inside a
    caller; what matters here is that a caller asking "which database do the
    agents read" gets the launcher's answer, not the other one's.

    Returns a copy. Nothing is exported: the point is to describe a child
    process, not to become one.
    """
    from dotenv import dotenv_values

    env = os.environ.copy()
    env_file = project_dir / ".env"
    if env_file.exists():
        env.update({
            key: value
            for key, value in dotenv_values(env_file).items()
            if value is not None
        })
    return env


def host_data_dir() -> Path:
    """Resolve the dedicated host-runtime root without source discovery.

    An explicit ``KESTREL_HOME`` is an operator custody decision and remains
    authoritative. Without it, host runtime belongs under
    ``~/.kestrel/host-data`` even when the current directory is a source clone.
    Resolution has no filesystem side effects; each storage owner must securely
    create and validate the returned directory before writing.
    """
    explicit_home = os.environ.get("KESTREL_HOME")
    base = (
        Path(explicit_home).expanduser()
        if explicit_home
        else Path.home() / ".kestrel"
    )
    return Path(os.path.abspath(base / "host-data"))


@lru_cache(maxsize=64)
def _resolve_cached(kestrel_home: str | None, cwd_str: str) -> Path:
    """Pure resolver — every input that affects the answer is an argument.

    Memoized so repeated lookups within one process don't restat the
    filesystem. ``lru_cache`` is keyed on the tuple of arguments, which
    means a subsequent ``os.chdir`` will produce a fresh lookup with the
    new ``cwd_str``. ``KESTREL_HOME`` is read once per resolution at
    the public-API boundary and passed in here, so an env-var change
    after the first call also produces a fresh entry.
    """
    if kestrel_home:
        return Path(kestrel_home).expanduser().resolve()

    cwd = Path(cwd_str).resolve()
    found = _walk_up_for_markers(cwd)
    if found is not None:
        return found

    pkg = package_dir()
    if not _is_inside_site_packages(pkg):
        # Source / editable install: parent of the package is the repo.
        return pkg.parent

    fallback = Path.home() / ".kestrel"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback.resolve()


def _walk_up_for_markers(start: Path) -> Path | None:
    """Search ``start`` and every ancestor for a project marker.

    Returns the first directory that contains any of ``_PROJECT_MARKERS``
    or a ``kestrel_sovereign`` package source. Stops at the filesystem
    root.
    """
    for candidate in (start, *start.parents):
        if any((candidate / marker).exists() for marker in _PROJECT_MARKERS):
            return candidate
        sentinel = candidate / _PACKAGE_SENTINEL
        if sentinel.is_dir() and (sentinel / "__init__.py").exists():
            return candidate
    return None


def _is_inside_site_packages(path: Path) -> bool:
    """True iff ``path`` is under any ``site-packages`` segment.

    Using the segment name rather than ``site.getsitepackages()`` so we
    correctly handle every flavor of install: system, user, virtualenv,
    venv-in-venv, pipx, uv-tool, conda. They all bury the package under
    a directory literally named ``site-packages``.
    """
    parts = path.parts
    return "site-packages" in parts


def reset_cache() -> None:
    """Clear the resolver cache.

    Tests that ``monkeypatch.setenv("KESTREL_HOME", ...)`` mid-run, or
    ``chdir`` and re-resolve, should call this to force a fresh lookup.
    Production code never needs it — the cache is keyed on the inputs,
    so a real change in either re-misses naturally.
    """
    _resolve_cached.cache_clear()
