"""Canonical, dependency-free semantic knowledge value contracts.

The names re-exported here are the one public package surface for semantic
assertions.  Storage, RDF codecs, inference, and training code must consume
these types rather than define competing assertion dataclasses.
"""

from .assertion import (
    IDENTITY_VERSION,
    IRI_PROFILE,
    LITERAL_PROFILE,
    MAPPING_SCHEMA_VERSION,
    RDF_LANG_STRING,
    XSD_BOOLEAN,
    XSD_DATE,
    XSD_DATETIME,
    XSD_DATETIME_STAMP,
    XSD_DECIMAL,
    XSD_INTEGER,
    XSD_STRING,
    XSD_TIME,
    Assertion,
    AssertionObject,
    AssertionQuery,
    AssertionResult,
    AssertionStatus,
    AssertionTerm,
    AssertionValidationError,
    BlankNode,
    DerivedLineage,
    DirectLineage,
    EpistemicState,
    IRI,
    Instant,
    Lineage,
    Literal,
    LocalIdentifier,
    OntologyRef,
    Resource,
    SourceOccurrence,
    SourceProvenance,
    TemporalInterval,
    Visibility,
    derive_assertion_id,
    identity_preimage,
    lineage_from_mapping,
    normalize_iri,
)

__all__ = [
    "Assertion",
    "AssertionObject",
    "AssertionQuery",
    "AssertionResult",
    "AssertionStatus",
    "AssertionTerm",
    "AssertionValidationError",
    "BlankNode",
    "DerivedLineage",
    "DirectLineage",
    "EpistemicState",
    "IDENTITY_VERSION",
    "IRI",
    "IRI_PROFILE",
    "Instant",
    "LITERAL_PROFILE",
    "Lineage",
    "Literal",
    "LocalIdentifier",
    "MAPPING_SCHEMA_VERSION",
    "OntologyRef",
    "RDF_LANG_STRING",
    "Resource",
    "SourceOccurrence",
    "SourceProvenance",
    "TemporalInterval",
    "Visibility",
    "XSD_BOOLEAN",
    "XSD_DATE",
    "XSD_DATETIME",
    "XSD_DATETIME_STAMP",
    "XSD_DECIMAL",
    "XSD_INTEGER",
    "XSD_STRING",
    "XSD_TIME",
    "derive_assertion_id",
    "identity_preimage",
    "lineage_from_mapping",
    "normalize_iri",
]
