"""Durable lifecycle Hold state.

Hold is a restart-surviving latch.  It is deliberately separate from the
momentary cooperative Stop authority in :mod:`kestrel_sovereign.stop`.
"""

from .enforcement import (
    HeldWorkDisposition,
    HoldEnforcementUnavailableError,
    HoldTurnRefusal,
    build_bound_host_context,
    close_bound_host_context,
    get_effective_hold_state,
    initialize_with_bound_hold_context,
    require_context_hold_store,
    require_turn_start_allowed,
    source_owns_hold_disposition,
)
from .introspection import (
    SELF_HOLD_HISTORY_LIMIT,
    SELF_HOLD_REDACTION_POLICY,
    InvalidHoldHistoryCursor,
    SelfHoldSnapshot,
    SelfHoldStateUnavailable,
    inspect_self_hold,
    read_self_hold,
)
from .state import (
    HOST_HOLD_TARGET,
    EffectiveHoldState,
    HoldAction,
    HoldAuthority,
    HoldCorruptStateError,
    HoldDisposition,
    HoldFeedEntry,
    HoldIdempotencyConflict,
    HoldMutation,
    HoldReceipt,
    HoldReceiptPage,
    HoldScope,
    HoldState,
    HoldStateError,
    HoldStore,
    hold_latch_payload,
    hold_receipt_payload,
)

__all__ = [
    "HOST_HOLD_TARGET",
    "SELF_HOLD_HISTORY_LIMIT",
    "SELF_HOLD_REDACTION_POLICY",
    "EffectiveHoldState",
    "HeldWorkDisposition",
    "HoldAction",
    "HoldAuthority",
    "HoldCorruptStateError",
    "HoldDisposition",
    "HoldEnforcementUnavailableError",
    "HoldFeedEntry",
    "HoldIdempotencyConflict",
    "HoldMutation",
    "HoldReceipt",
    "HoldReceiptPage",
    "HoldScope",
    "HoldState",
    "HoldStateError",
    "HoldStore",
    "HoldTurnRefusal",
    "InvalidHoldHistoryCursor",
    "SelfHoldSnapshot",
    "SelfHoldStateUnavailable",
    "build_bound_host_context",
    "close_bound_host_context",
    "get_effective_hold_state",
    "hold_latch_payload",
    "hold_receipt_payload",
    "initialize_with_bound_hold_context",
    "inspect_self_hold",
    "read_self_hold",
    "require_context_hold_store",
    "require_turn_start_allowed",
    "source_owns_hold_disposition",
]
