"""
Kestrel Configuration Module.

Centralized configuration and constants for the Kestrel framework.
"""

from .constants import *

__all__ = [
    # Network timeouts
    "REDIS_CONNECT_TIMEOUT",
    "HTTP_TIMEOUT_SHORT",
    "HTTP_TIMEOUT_DEFAULT",
    "HTTP_TIMEOUT_MEDIUM",
    "HTTP_TIMEOUT_LONG",
    "HTTP_TIMEOUT_DOWNLOAD",
    "TASK_WORKER_STOP_TIMEOUT",
    "SHUTDOWN_TIMEOUT",
    "CLIENT_CLOSE_TIMEOUT",
    "SSH_COMMAND_TIMEOUT_SHORT",
    "SSH_COMMAND_TIMEOUT_DEFAULT",
    "SSH_COMMAND_TIMEOUT_MEDIUM",
    "SSH_COMMAND_TIMEOUT_SETUP",
    "SSH_COMMAND_TIMEOUT_LONG",
    # Polling and retry
    "POLL_INTERVAL_FAST",
    "POLL_INTERVAL_MEDIUM",
    "POLL_INTERVAL_DEFAULT",
    "POLL_INTERVAL_MINUTE",
    "REFLECTION_INTERVAL",
    # Cache and sessions
    "SESSION_CACHE_TTL",
    # Training
    "TRAINING_TIMEOUT",
    "TRAINING_GENERATION_TIMEOUT",
    "TRAINING_TIMEOUT_EXTENDED",
    "TRAINING_TIMEOUT_LORA",
    "TRAINING_POLL_INTERVAL",
    "TRAINING_POLL_INTERVAL_FAST",
    "DEFAULT_TRAINING_STEPS",
    "DEFAULT_IMAGE_SIZE",
    # Rate limits
    "REGISTRATION_RATE_LIMIT",
    "LOGIN_RATE_LIMIT",
    # MCP session management
    "SESSION_CONNECT_TIMEOUT_SHORT",
    "SESSION_CONNECT_TIMEOUT_DEFAULT",
]
