#!/usr/bin/env python3
"""Check repository-local relative Markdown links for broken targets.

The docs OKF pipeline (``scripts/docs_okf.py`` / ``scripts/docs_verify.py``)
validates machine-readable metadata and generated indexes for *OKF* documents.
It does **not** guard the top-level onboarding files (README, QUICKSTART,
CONTRIBUTING, AGENTS) or the full ``docs/`` tree against relative links that
rot when a target file is moved or a heading is renamed. This checker fills
that gap.

For every Markdown link and reference definition in the covered files it:

* resolves relative paths and root-absolute (``/foo``) paths against the repo,
* resolves ``#fragment`` anchors against the target Markdown file's headings
  and explicit ``<a id=...>`` / ``<a name=...>`` anchors (GitHub slug rules),
* percent-decodes targets and understands ``<...>`` angle-bracket and balanced
  parenthesis link destinations,
* ignores external URLs (``http:``, ``https:``, ``mailto:``, ``tel:``, ``//``,
  ``data:`` …) — it never performs any network I/O, and
* skips a small, explicit set of generated/vendor directories.

It reports the source file, line, raw link target, and the resolved missing
target, and exits non-zero when any local link is broken.

Local usage::

    uv run python scripts/check_docs_links.py            # check the default set
    uv run python scripts/check_docs_links.py README.md  # check specific files
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Top-level onboarding files that are checked in addition to ``docs/**/*.md``.
# These are the files the issue calls out explicitly plus ``CLAUDE.md``, the
# root pointer to ``AGENTS.md``.
TOP_LEVEL_SOURCES = (
    "README.md",
    "QUICKSTART.md",
    "CONTRIBUTING.md",
    "AGENTS.md",
    "CLAUDE.md",
)

# Directory (relative to the repo root) whose Markdown is scanned recursively.
DOCS_DIR = "docs"

# Generated / vendored directories are excluded from *source* scanning: their
# link sets are a volatile function of a generator (or an imported dump),
# reviewed and regenerated by their own tooling (``docs_okf.py`` /
# ``docs_verify.py``), so link rot there is caught at generation time, not here.
# These are the "clearly documented generated/templated exceptions" from the
# issue. Active, hand-maintained trees (``docs/audit`` ledgers, ``docs/demos``
# scripts) are NOT excluded here — only genuinely generated *files* inside them
# are skipped, via :func:`_is_generated_doc`, and genuinely-generated *targets*
# those files link to are skipped via :func:`_is_generated_target`. Paths are
# POSIX, relative to the repo root.
EXCLUDED_SOURCE_DIRS = (
    "docs/generated",  # OKF-generated indexes, logs, and render manifests.
    "docs/research",  # Imported third-party research dumps (external citations,
    #                   reference-style prose, not maintained navigation).
    "docs/audit/issues",  # Archived GitHub *issue bodies* (see docs/audit/README):
    #                       point-in-time snapshots that quote code paths as bare
    #                       relative links exactly as they appeared in the issue.
    #                       The active audit ledgers in docs/audit/*.md ARE scanned.
    "node_modules",
    ".venv",
    ".git",
)

# Narrow, documented *target* exception. Some scanned source pages legitimately
# link to artifacts that are generated on demand and gitignored, so a fresh
# checkout will not contain them. Rather than exclude the whole referring page
# from scanning (which would blind the guard to that page's real links), the
# individual target is skipped. Kept deliberately narrow along THREE axes so it
# cannot mask an ordinary broken link:
#
# * location — the target must live under a ``demos/**/demo-output/`` capture
#   directory (both the ``demos/`` root and a ``demo-output/`` component are
#   required); a ``demo-output/`` directory anywhere else is NOT exempt,
# * file type — only screenshot *image* evidence qualifies
#   (:data:`_GENERATED_TARGET_IMAGE_SUFFIXES`); a missing ``.py``/``.md``/config
#   file inside ``demo-output/`` is still a real broken link and is reported.
#
# This matches ``.gitignore`` (``demo-output/``) and the demo runner, which
# writes the screenshots (``demos/technical/demo-output/01-did-identity.png`` …)
# referenced by ``docs/demos/DEMO_SCRIPT.md``. Everything else — including
# committed images — is validated.
_GENERATED_TARGET_ROOT = "demos"
_GENERATED_TARGET_DIR = "demo-output"
_GENERATED_TARGET_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}

# Individual generated files live inside otherwise-active directories (e.g. the
# nightly ``docs/audit/REPO_MAP.md`` and the per-directory OKF ``index.md``
# files). Their links are a function of a generator and are validated at
# generation time by ``docs_okf.py``, so they are skipped here too — detected by
# content rather than by hardcoded paths, so a newly generated index or ledger
# is covered automatically.
_GENERATED_FRONTMATTER_RE = re.compile(r"^generated:\s*true\s*$", re.IGNORECASE | re.MULTILINE)
_OKF_INDEX_MARKER = "Generated by `uv run python scripts/docs_okf.py index`"

MARKDOWN_SUFFIXES = {".md", ".markdown"}

# This checker validates that every repository-local link *target* exists, and
# that Markdown ``#fragment`` anchors resolve. What that means per target kind:
#
# * Markdown targets (``.md`` / ``.markdown``) are validated for existence and,
#   for a ``#fragment`` link, for a matching heading / HTML anchor.
# * Every other repository-local target — an embedded image or PDF, and a
#   source/config cross-reference (``file.py``, ``config.toml``, a shell script,
#   …) — is validated for *existence*. A link to a moved or renamed file is a
#   real defect whether the target is a doc asset or code, so the path is always
#   checked. Only anchor/fragment *content* validation is Markdown-only: a
#   ``#L182`` blob line reference, or any ``#fragment`` on a code/config target,
#   is never anchor-checked (see :func:`resolve_link`).
# * A target that resolves *outside* the repository root (``../../sibling-repo``)
#   is not repository-local — the open-core split puts wallet/voice/SDK modules
#   in sibling repos, referenced by verified external URL — so it cannot be
#   validated here and is skipped. Genuinely-generated, gitignored artifacts
#   (demo screenshot images under ``demos/**/demo-output/``) are skipped via a
#   narrow, documented target exception (see
#   :data:`_GENERATED_TARGET_IMAGE_SUFFIXES` / :func:`_is_generated_target`).

# URL schemes (and protocol-relative ``//``) that are external and never
# resolved locally or fetched.
_SCHEME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9+.\-]*:")

# A GitHub blob *line* reference (``#L182``, ``#L77-L89``). It is a view offset
# into the raw file, not a rendered-Markdown heading anchor, so it is never
# anchor-validated — even on a Markdown target (``README.md#L9``).
_LINE_REF_RE = re.compile(r"^L\d+(?:-L?\d+)?$")

# Heading line: 1-6 ``#`` then text (ATX). Trailing ``#`` run is closing syntax.
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
# Fenced code block delimiter (``` or ~~~), possibly indented up to 3 spaces.
_FENCE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
# Reference-style link definition: ``[label]: destination "optional title"``.
# The body after the label is validated further in :func:`_parse_ref_definition`
# so prose that merely looks like a definition (``[bug]: the tracker is …``) is
# not mistaken for a link.
_REF_DEF_RE = re.compile(r"^\s{0,3}\[[^\]]+\]:\s+(.+)$")
# Explicit HTML anchors GitHub honors: ``<a id="x">`` / ``<a name="x">`` and
# an ``id``/``name`` attribute on any element (e.g. ``<h2 id="x">``).
_HTML_ANCHOR_RE = re.compile(
    r"<[a-zA-Z][^>]*?\b(?:id|name)\s*=\s*[\"']([^\"']+)[\"']", re.IGNORECASE
)


@dataclass(frozen=True)
class Link:
    """A single link occurrence in a source file."""

    line: int
    raw_target: str


@dataclass(frozen=True)
class BrokenLink:
    """A resolved-but-missing local link, ready to report."""

    source: str  # repo-relative POSIX path of the file containing the link
    line: int
    raw_target: str
    resolved: str  # human-readable resolved missing target
    reason: str  # "missing file" or "missing anchor"

    def format(self) -> str:
        return (
            f"{self.source}:{self.line}: {self.reason}: "
            f"`{self.raw_target}` -> {self.resolved}"
        )


def github_slug(text: str) -> str:
    """Slugify heading text the way GitHub's Markdown renderer does.

    Lowercase, drop every character that is not a Unicode word character,
    hyphen, or space (this removes emoji, punctuation, and parentheses), then
    replace spaces with hyphens. Spaces are *not* collapsed first, matching
    GitHub's ``github-slugger`` (``"a — b"`` -> ``"a--b"``).
    """

    text = text.lower()
    text = re.sub(r"[^\w\- ]", "", text, flags=re.UNICODE)
    return text.replace(" ", "-")


class GithubSlugger:
    """Reproduce ``github-slugger`` duplicate handling (``base``, ``base-1`` …)."""

    def __init__(self) -> None:
        self._seen: dict[str, int] = {}

    def slug(self, text: str) -> str:
        base = github_slug(text)
        if base in self._seen:
            self._seen[base] += 1
            return f"{base}-{self._seen[base]}"
        self._seen[base] = 0
        return base


def _strip_heading_markup(text: str) -> str:
    """Remove link/HTML markup from heading text before slugging.

    Backticks, asterisks, and parentheses are left for :func:`github_slug` to
    strip; only link *destinations* and HTML tags must be removed first so
    their contents do not leak into the slug.
    """

    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)  # [t](url) -> t
    text = re.sub(r"\[([^\]]*)\]\[[^\]]*\]", r"\1", text)  # [t][ref] -> t
    text = re.sub(r"<[^>]+>", "", text)  # drop HTML tags
    return text


def _iter_non_fenced_lines(text: str):
    """Yield ``(lineno, line)`` for lines outside fenced code blocks."""

    fence: str | None = None
    for lineno, line in enumerate(text.splitlines(), start=1):
        match = _FENCE_RE.match(line)
        if match:
            token = match.group(1)[0] * 3
            if fence is None:
                fence = token
            elif line.strip().startswith(fence):
                fence = None
            continue
        if fence is not None:
            continue
        yield lineno, line


def anchors_for(text: str) -> set[str]:
    """Return the set of anchor slugs a Markdown document exposes."""

    anchors: set[str] = set()
    slugger = GithubSlugger()
    for _lineno, line in _iter_non_fenced_lines(text):
        heading = _HEADING_RE.match(line)
        if heading:
            anchors.add(slugger.slug(_strip_heading_markup(heading.group(2))))
        for match in _HTML_ANCHOR_RE.finditer(line):
            anchors.add(match.group(1).lower())
    return anchors


def _mask_inline_code(line: str) -> str:
    """Blank out inline code spans so link syntax inside them is ignored."""

    out: list[str] = []
    i = 0
    n = len(line)
    while i < n:
        char = line[i]
        if char == "`":
            run = 1
            while i + run < n and line[i + run] == "`":
                run += 1
            ticks = "`" * run
            close = line.find(ticks, i + run)
            if close == -1:
                out.append(line[i:])
                break
            out.append(" " * (close + run - i))
            i = close + run
            continue
        out.append(char)
        i += 1
    return "".join(out)


def _split_destination(inner: str) -> str:
    """Extract the destination from a ``(dest "title")`` link body."""

    inner = inner.strip()
    if not inner:
        return ""
    if inner.startswith("<"):
        end = inner.find(">")
        return inner[1:end] if end != -1 else inner[1:]
    # A non-bracketed destination cannot contain whitespace; the title (if any)
    # follows the first whitespace run.
    return inner.split()[0]


def _find_inline_targets(line: str) -> list[str]:
    """Return raw link/image destinations on a single (code-masked) line."""

    targets: list[str] = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] != "[":
            i += 1
            continue
        # Find the matching ``]`` for the label, allowing nested brackets.
        depth = 1
        j = i + 1
        while j < n and depth:
            if line[j] == "[":
                depth += 1
            elif line[j] == "]":
                depth -= 1
            j += 1
        if depth != 0:
            break
        if j < n and line[j] == "(":
            k = j + 1
            if k < n and line[k] == "<":
                end = line.find(">", k + 1)
                if end == -1:
                    i = j + 1
                    continue
                close = line.find(")", end + 1)
                targets.append(_split_destination(line[j + 1 : close if close != -1 else n]))
                i = (close + 1) if close != -1 else n
                continue
            pdepth = 1
            start = k
            while k < n and pdepth:
                if line[k] == "(":
                    pdepth += 1
                elif line[k] == ")":
                    pdepth -= 1
                k += 1
            if pdepth != 0:
                i = j + 1
                continue
            targets.append(_split_destination(line[start : k - 1]))
            i = k
        else:
            i = j
    return targets


def _parse_ref_definition(body: str) -> str | None:
    """Return the destination of a link reference definition, or ``None``.

    Rejects prose that only resembles a definition: after the destination the
    remainder must be empty or a valid title (``"…"`` / ``'…'`` / ``(…)``).
    """

    body = body.strip()
    if body.startswith("<"):
        end = body.find(">")
        if end == -1:
            return None
        dest = body[1:end]
        rest = body[end + 1 :].strip()
    else:
        parts = body.split(None, 1)
        dest = parts[0]
        rest = parts[1].strip() if len(parts) > 1 else ""
    if rest and rest[0] not in "\"'(":
        return None
    return dest


def extract_links(text: str) -> list[Link]:
    """Parse all checkable link targets from Markdown ``text``."""

    links: list[Link] = []
    for lineno, line in _iter_non_fenced_lines(text):
        ref_def = _REF_DEF_RE.match(line)
        if ref_def:
            dest = _parse_ref_definition(ref_def.group(1))
            if dest:
                links.append(Link(lineno, dest))
            continue
        for target in _find_inline_targets(_mask_inline_code(line)):
            if target:
                links.append(Link(lineno, target))
    return links


def _is_external(target: str) -> bool:
    if target.startswith("//"):  # protocol-relative
        return True
    scheme = _SCHEME_RE.match(target)
    return bool(scheme)


def _within_project_root(path: Path) -> bool:
    """Whether ``path`` is inside the repository root (not a sibling repo)."""

    try:
        path.relative_to(PROJECT_ROOT)
        return True
    except ValueError:
        return False


def _display(path: Path) -> str:
    """A repo-relative POSIX path for reporting, falling back to the absolute."""

    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path)


def _is_generated_target(resolved_path: Path) -> bool:
    """Whether a link *target* is an intentionally-uncommitted generated artifact.

    Demo scripts embed capture-time screenshot *images* under a
    ``demos/**/demo-output/`` directory, which is gitignored (``.gitignore``:
    ``demo-output/``) and regenerated on demand by the demo runner. Such a target
    is documentation evidence that legitimately may be absent from a checkout, so
    its existence is not validated. The exception is deliberately narrow on both
    location and file type so it cannot mask an ordinary broken link:

    * the target must sit under a ``demos/**/demo-output/`` capture directory —
      both a ``demos/`` root component and a ``demo-output/`` component are
      required, so a ``demo-output/`` directory elsewhere in the tree (e.g.
      ``docs/assets/demo-output/``) is NOT exempt, and
    * the target must be an image (:data:`_GENERATED_TARGET_IMAGE_SUFFIXES`); a
      missing ``.py``/``.md``/config file inside ``demo-output/`` is a real
      broken link and is still reported.
    """

    if resolved_path.suffix.lower() not in _GENERATED_TARGET_IMAGE_SUFFIXES:
        return False
    try:
        parent_parts = resolved_path.relative_to(PROJECT_ROOT).parts[:-1]
    except ValueError:
        return False
    return bool(parent_parts) and parent_parts[0] == _GENERATED_TARGET_ROOT and (
        _GENERATED_TARGET_DIR in parent_parts
    )


def resolve_link(source: Path, raw_target: str) -> BrokenLink | None:
    """Resolve one link; return a :class:`BrokenLink` if it is broken locally."""

    target = raw_target.strip()
    if not target:
        return None
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    if _is_external(target):
        return None

    path_part, _, fragment = target.partition("#")
    path_part = unquote(path_part).strip()
    fragment = fragment.strip()
    source_rel = source.relative_to(PROJECT_ROOT).as_posix()

    if not path_part:
        # Pure ``#fragment`` — resolve against the source file itself.
        resolved_path = source
    else:
        if path_part.startswith("/"):
            resolved_path = (PROJECT_ROOT / path_part.lstrip("/")).resolve()
        else:
            resolved_path = (source.parent / path_part).resolve()
        # A target that escapes the repository root points outside this repo
        # (e.g. a sibling feature/SDK package under the open-core split). It is
        # not a repository-local link, so it cannot be validated here.
        if not _within_project_root(resolved_path):
            return None
        # A gitignored, generated-on-demand artifact (demo screenshot evidence)
        # is legitimately absent from a checkout; skip its existence check via a
        # narrow, documented target exception rather than by not scanning its
        # referring page.
        if _is_generated_target(resolved_path):
            return None

    # Every repository-local target must exist — Markdown pages, embedded doc
    # assets, AND source/config cross-references (``file.py``, ``config.toml``, a
    # shell script). A link to a moved or renamed path is a real defect
    # regardless of the target's file type. Directory (extensionless) targets are
    # validated the same way. External and sibling-repo targets already returned
    # above.
    if not resolved_path.exists():
        return BrokenLink(source_rel, 0, raw_target, _display(resolved_path), "missing file")

    # Anchor/fragment *content* validation applies only to Markdown targets, and
    # never to GitHub blob line references (``#L182``) — those are raw-file view
    # offsets, not rendered-Markdown heading anchors, whether the target is code
    # or Markdown (so ``guide.py#L10`` and ``README.md#L9`` both only require the
    # path to exist). The file's existence has already been checked above.
    if (
        fragment
        and not _LINE_REF_RE.match(fragment)
        and resolved_path.is_file()
        and resolved_path.suffix.lower() in MARKDOWN_SUFFIXES
    ):
        anchors = anchors_for(resolved_path.read_text(encoding="utf-8", errors="replace"))
        if fragment.lower() not in anchors:
            return BrokenLink(
                source_rel, 0, raw_target, f"{_display(resolved_path)}#{fragment}", "missing anchor"
            )
    return None


def check_text(source: Path, text: str) -> list[BrokenLink]:
    """Check every link in ``text`` (attributed to ``source``)."""

    broken: list[BrokenLink] = []
    for link in extract_links(text):
        result = resolve_link(source, link.raw_target)
        if result is not None:
            broken.append(
                BrokenLink(
                    result.source,
                    link.line,
                    result.raw_target,
                    result.resolved,
                    result.reason,
                )
            )
    return broken


def check_file(path: Path) -> list[BrokenLink]:
    text = path.read_text(encoding="utf-8", errors="replace")
    return check_text(path, text)


def _is_excluded(path: Path) -> bool:
    rel = path.relative_to(PROJECT_ROOT).as_posix()
    return any(rel == d or rel.startswith(d + "/") for d in EXCLUDED_SOURCE_DIRS)


def _is_generated_doc(path: Path) -> bool:
    """Whether ``path`` is a generated artifact (regenerated by its own tooling).

    Detected by content rather than a hardcoded path list: a ``generated: true``
    frontmatter key (e.g. ``docs/audit/REPO_MAP.md``) or the OKF ``index.md``
    generator banner. Such files are validated at generation time by
    ``docs_okf.py``, so their links are not re-checked here.
    """

    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2048]
    except OSError:
        return False
    return bool(_GENERATED_FRONTMATTER_RE.search(head)) or _OKF_INDEX_MARKER in head


def iter_source_files() -> list[Path]:
    """Return the default set of files to check, sorted and deduplicated."""

    files: list[Path] = []
    for name in TOP_LEVEL_SOURCES:
        candidate = PROJECT_ROOT / name
        if candidate.is_file():
            files.append(candidate)
    docs_root = PROJECT_ROOT / DOCS_DIR
    if docs_root.is_dir():
        for md in sorted(docs_root.rglob("*.md")):
            if not _is_excluded(md) and not _is_generated_doc(md):
                files.append(md)
    # Preserve order while removing duplicates.
    seen: set[Path] = set()
    unique: list[Path] = []
    for path in files:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(path)
    return unique


def check_paths(paths: list[Path]) -> list[BrokenLink]:
    broken: list[BrokenLink] = []
    for path in paths:
        broken.extend(check_file(path))
    return broken


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "paths",
        nargs="*",
        help="Specific Markdown files to check (default: onboarding files + docs/**).",
    )
    args = parser.parse_args(argv)

    if args.paths:
        targets = [Path(p).resolve() for p in args.paths]
    else:
        targets = iter_source_files()

    broken = check_paths(targets)
    if broken:
        for item in sorted(broken, key=lambda b: (b.source, b.line, b.raw_target)):
            print(item.format())
        print(
            f"\nFound {len(broken)} broken local link(s) across "
            f"{len({b.source for b in broken})} file(s).",
            file=sys.stderr,
        )
        return 1
    print(f"OK: checked {len(targets)} file(s); no broken local links.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
